stages: # Stages 表示构建阶段，这里有两个阶段 install, deploy
  - install
  - deploy

install-staging:dep:
  stage: install
  tags:
    - test
#  only: # 定义了只有在被merge到了master分支上 才会执行部署脚本。
#    - master
  script:
    - npm install  #安装依赖
  artifacts:  # 将这个job生成的依赖传递给下一个job。需要设置dependencies
    expire_in: 60 mins   # artifacets 的过期时间，因为这些数据都是直接保存在 Gitlab 机器上的，过于久远的资源就可以删除掉了
    paths:  # 需要被传递给下一个job的目录。
      - node_modules/

deploy-staging:dep:
  stage: deploy
  tags:
    - test
#  only:
#    - master
  script:
    - npm run build  # 将项目打包
    - sudo cp -rf ./dist/  /usr/local/webapp